# Generated by Django 2.0 on 2017-12-20 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20170828_1448'), ('blog', '0003_post_uid'), ('blog', '0004_auto_20170902_0932'), ('blog', '0005_auto_20170902_0940'), ('blog', '0006_page_files'), ('blog', '0007_auto_20170908_1427'), ('blog', '0008_auto_20170913_1010')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('list_post', models.BooleanField(default=True)),
                ('draft', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(default='scarpetta', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('oauth2_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=32)),
                ('level', models.IntegerField(default=2)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('blocked', models.BooleanField(default=False)),
                ('hide_content', models.BooleanField(default=False)),
                ('hide_picture', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(related_name='posts', to='blog.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='_post_comments_+', to='blog.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='list_post',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(related_name='_post_files_+', to='blog.File'),
        ),
        migrations.AddField(
            model_name='page',
            name='files',
            field=models.ManyToManyField(related_name='_page_files_+', to='blog.File'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edit_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
